In [1]:
import numpy as np

In [4]:
arr=np.array([1,3,4,5,]) #array of rank 1

In [5]:
print(arr)

[1 3 4 5]


In [7]:
arr2=np.array([[1,2,3],[3,5,2]]) #array of rank 2

In [8]:
print(arr2)

[[1 2 3]
 [3 5 2]]


In [9]:
# array from tupple
arr3=np.array((3,3,2))

In [10]:
print(arr3)

[3 3 2]


In [11]:
#array from set
arr4=np.array({3,3,2})

In [12]:
print(arr3)

{2, 3}


In [13]:
#array from dict
arr5=np.array({'a':4,'b':5})

In [14]:
print(arr5)

{'a': 4, 'b': 5}


In [23]:
arr6 = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

Index_arr = arr6[[1, 1, 0, 3],
                [3, 2, 1, 0]]
print ("\nElements at indices (1, 3), " "(1, 2), (0, 1), (3, 0):\n", Index_arr)


Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]


In [32]:
sliced_arr = arr6[:2, ::2] # arr[row_start_idx:end_idx:step,column_start_idx:end_idx:step]
print ("Array with first 2 rows and"
    " alternate columns(0 and 2):\n", sliced_arr)

Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


# Basic Array Operations

In [33]:
a = np.array([[1, 2],
              [5,1]])
 
b = np.array([[1, 2],
              [2, 1]])

In [37]:
arradd=a+b
arrsub=a-b
arrmul=a*b
arrdiv=a/b
# all row and column will get operated with each other
print(arradd)
print(arrsub)
print(arrmul)
print(arrdiv)

[[2 4]
 [7 2]]
[[0 0]
 [3 0]]
[[ 1  4]
 [10  1]]
[[1.  1. ]
 [2.5 1. ]]


In [43]:
# individual operation
a=a+1 #will add 1 to all matrix element
print(a)
a=a-2
print(a)
print(a.sum()) # will add all elements of matrix

[[2 3]
 [6 2]]
[[0 1]
 [4 0]]
5


In [47]:

array=np.array([[1,3,4],[3,6,1]])

print("Array is of type: ", array.dtype) 
 
print("No. of dimensions: ", array.ndim) # array dimensions (axes)
 

print("Shape of array: ", array.shape) # shape of array
 

print("Size of array: ", array.size) # size (total number of elements) of array
 

print("Array stores elements of type: ", array.dtype) # type of elements in array

Array is of type:  int32
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


In [49]:
x = np.array([1, 2])  
print("Datatype is : ",x.dtype)
x = np.array([1.0, 2.0]) 
print("Datatype is : ",x.dtype)
 
x = np.array([1, 2], dtype = np.int64)   # Forced Datatype
print("Datatype is : ",x.dtype)


Datatype is :  int32
Datatype is :  float64
Datatype is :  int64


In [52]:
arr1 = np.array([[4, 7], [2, 6]], dtype = np.int64)
arr2 = np.array([[3, 6], [2, 8]], dtype = np.int64) 

Sum = np.add(arr1, arr2)
print("Addition of Two Arrays: ",Sum)

Sum1 = np.sum(arr1)
print("Addition of Array elements: ",Sum1)
Sqrt = np.sqrt(arr1)
print("Square root of Array1 elements: ",Sqrt)

Trans_arr = arr1.T # Transpose of Array
print("\nTranspose of Array: ")
print(Trans_arr)

Addition of Two Arrays:  [[ 7 13]
 [ 4 14]]
Addition of Array elements:  19
Square root of Array1 elements:  [[2.         2.64575131]
 [1.41421356 2.44948974]]

Transpose of Array: 
[[4 2]
 [7 6]]
